<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $now = now();

        $rows = [
            [
                'provider' => 'openai',
                'model' => 'gpt-4.1-mini',
                'label' => 'GPT-4.1 Mini',
                'credits_per_1k_input' => 0.0400,
                'credits_per_1k_output' => 0.1600,
                'usd_per_1m_input' => 0.40,
                'usd_per_1m_output' => 1.60,
                'usd_per_1m_reasoning' => null,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'openai',
                'model' => 'gpt-4.1',
                'label' => 'GPT-4.1',
                'credits_per_1k_input' => 0.2000,
                'credits_per_1k_output' => 0.8000,
                'usd_per_1m_input' => 2.00,
                'usd_per_1m_output' => 8.00,
                'usd_per_1m_reasoning' => null,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'openai',
                'model' => 'gpt-4.1-nano',
                'label' => 'GPT-4.1 Nano',
                'credits_per_1k_input' => 0.0100,
                'credits_per_1k_output' => 0.0400,
                'usd_per_1m_input' => 0.10,
                'usd_per_1m_output' => 0.40,
                'usd_per_1m_reasoning' => null,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'openai',
                'model' => 'gpt-4o-mini',
                'label' => 'GPT-4o Mini',
                'credits_per_1k_input' => 0.0150,
                'credits_per_1k_output' => 0.0600,
                'usd_per_1m_input' => 0.15,
                'usd_per_1m_output' => 0.60,
                'usd_per_1m_reasoning' => null,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'openai',
                'model' => 'gpt-4o',
                'label' => 'GPT-4o',
                'credits_per_1k_input' => 0.2500,
                'credits_per_1k_output' => 1.0000,
                'usd_per_1m_input' => 2.50,
                'usd_per_1m_output' => 10.00,
                'usd_per_1m_reasoning' => null,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'openai',
                'model' => 'o3-mini',
                'label' => 'o3-mini',
                'credits_per_1k_input' => 0.1100,
                'credits_per_1k_output' => 0.4400,
                'usd_per_1m_input' => 1.10,
                'usd_per_1m_output' => 4.40,
                'usd_per_1m_reasoning' => null,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'openai',
                'model' => 'o3',
                'label' => 'o3',
                'credits_per_1k_input' => 0.2000,
                'credits_per_1k_output' => 0.8000,
                'usd_per_1m_input' => 2.00,
                'usd_per_1m_output' => 8.00,
                'usd_per_1m_reasoning' => null,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'openai',
                'model' => 'o4-mini',
                'label' => 'o4-mini',
                'credits_per_1k_input' => 0.1100,
                'credits_per_1k_output' => 0.4400,
                'usd_per_1m_input' => 1.10,
                'usd_per_1m_output' => 4.40,
                'usd_per_1m_reasoning' => null,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'openai',
                'model' => 'o3-pro',
                'label' => 'o3-pro',
                'credits_per_1k_input' => 2.0000,
                'credits_per_1k_output' => 8.0000,
                'usd_per_1m_input' => 20.00,
                'usd_per_1m_output' => 80.00,
                'usd_per_1m_reasoning' => null,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'openai',
                'model' => 'gpt-5-mini',
                'label' => 'GPT-5 Mini',
                'credits_per_1k_input' => 0.0250,
                'credits_per_1k_output' => 0.2000,
                'usd_per_1m_input' => 0.25,
                'usd_per_1m_output' => 2.00,
                'usd_per_1m_reasoning' => null,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'openai',
                'model' => 'gpt-5-nano',
                'label' => 'GPT-5 Nano',
                'credits_per_1k_input' => 0.0050,
                'credits_per_1k_output' => 0.0400,
                'usd_per_1m_input' => 0.05,
                'usd_per_1m_output' => 0.40,
                'usd_per_1m_reasoning' => null,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'openai',
                'model' => 'gpt-5',
                'label' => 'GPT-5',
                'credits_per_1k_input' => 0.1250,
                'credits_per_1k_output' => 1.0000,
                'usd_per_1m_input' => 1.25,
                'usd_per_1m_output' => 10.00,
                'usd_per_1m_reasoning' => null,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'openai',
                'model' => 'gpt-5-pro',
                'label' => 'GPT-5 Pro',
                'credits_per_1k_input' => 1.5000,
                'credits_per_1k_output' => 12.0000,
                'usd_per_1m_input' => 15.00,
                'usd_per_1m_output' => 120.00,
                'usd_per_1m_reasoning' => null,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'openai',
                'model' => 'gpt-5.1',
                'label' => 'GPT-5.1',
                'credits_per_1k_input' => 0.1250,
                'credits_per_1k_output' => 1.0000,
                'usd_per_1m_input' => 1.25,
                'usd_per_1m_output' => 10.00,
                'usd_per_1m_reasoning' => null,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'openai',
                'model' => 'gpt-5.2',
                'label' => 'GPT-5.2',
                'credits_per_1k_input' => 0.1750,
                'credits_per_1k_output' => 1.4000,
                'usd_per_1m_input' => 1.75,
                'usd_per_1m_output' => 14.00,
                'usd_per_1m_reasoning' => null,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'openai',
                'model' => 'gpt-5.2-pro',
                'label' => 'GPT-5.2 Pro',
                'credits_per_1k_input' => 2.1000,
                'credits_per_1k_output' => 16.8000,
                'usd_per_1m_input' => 21.00,
                'usd_per_1m_output' => 168.00,
                'usd_per_1m_reasoning' => null,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'openai',
                'model' => 'gpt-5.4-nano',
                'label' => 'GPT-5.4 Nano',
                'credits_per_1k_input' => 0.0200,
                'credits_per_1k_output' => 0.1250,
                'usd_per_1m_input' => 0.20,
                'usd_per_1m_output' => 1.25,
                'usd_per_1m_reasoning' => null,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'openai',
                'model' => 'gpt-5.4-mini',
                'label' => 'GPT-5.4 Mini',
                'credits_per_1k_input' => 0.0750,
                'credits_per_1k_output' => 0.4500,
                'usd_per_1m_input' => 0.75,
                'usd_per_1m_output' => 4.50,
                'usd_per_1m_reasoning' => null,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'openai',
                'model' => 'gpt-5.4-pro',
                'label' => 'GPT-5.4 Pro',
                'credits_per_1k_input' => 3.0000,
                'credits_per_1k_output' => 18.0000,
                'usd_per_1m_input' => 30.00,
                'usd_per_1m_output' => 180.00,
                'usd_per_1m_reasoning' => null,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'openai',
                'model' => 'gpt-5.4',
                'label' => 'GPT-5.4',
                'credits_per_1k_input' => 0.2500,
                'credits_per_1k_output' => 1.5000,
                'usd_per_1m_input' => 2.50,
                'usd_per_1m_output' => 15.00,
                'usd_per_1m_reasoning' => null,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'openai',
                'model' => 'gpt-5.5-pro',
                'label' => 'GPT-5.5 Pro',
                'credits_per_1k_input' => 3.0000,
                'credits_per_1k_output' => 18.0000,
                'usd_per_1m_input' => 30.00,
                'usd_per_1m_output' => 180.00,
                'usd_per_1m_reasoning' => null,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'openai',
                'model' => 'gpt-5.5',
                'label' => 'GPT-5.5',
                'credits_per_1k_input' => 0.5000,
                'credits_per_1k_output' => 3.0000,
                'usd_per_1m_input' => 5.00,
                'usd_per_1m_output' => 30.00,
                'usd_per_1m_reasoning' => null,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'gemini',
                'model' => 'gemini-2.5-flash',
                'label' => 'Gemini 2.5 Flash',
                'credits_per_1k_input' => 0.0300,
                'credits_per_1k_output' => 0.2500,
                'usd_per_1m_input' => 0.30,
                'usd_per_1m_output' => 2.50,
                'usd_per_1m_reasoning' => 2.50,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'gemini',
                'model' => 'gemini-2.5-pro',
                'label' => 'Gemini 2.5 Pro',
                'credits_per_1k_input' => 0.1250,
                'credits_per_1k_output' => 1.0000,
                'usd_per_1m_input' => 1.25,
                'usd_per_1m_output' => 10.00,
                'usd_per_1m_reasoning' => 10.00,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'gemini',
                'model' => 'gemini-3.1-pro-preview',
                'label' => 'Gemini 3.1 Pro Preview',
                'credits_per_1k_input' => 0.2000,
                'credits_per_1k_output' => 1.2000,
                'usd_per_1m_input' => 2.00,
                'usd_per_1m_output' => 12.00,
                'usd_per_1m_reasoning' => 12.00,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => 14.00,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'gemini',
                'model' => 'gemini-3-pro-preview',
                'label' => 'Gemini 3 Pro Preview',
                'credits_per_1k_input' => 0.2000,
                'credits_per_1k_output' => 1.2000,
                'usd_per_1m_input' => 2.00,
                'usd_per_1m_output' => 12.00,
                'usd_per_1m_reasoning' => 12.00,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => 14.00,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'gemini_deep_research',
                'model' => 'deep-research-preview-04-2026',
                'label' => 'Gemini Deep Research',
                'credits_per_1k_input' => 0.2000,
                'credits_per_1k_output' => 1.2000,
                'usd_per_1m_input' => 2.00,
                'usd_per_1m_output' => 12.00,
                'usd_per_1m_reasoning' => 12.00,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => 14.00,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'gemini_deep_research',
                'model' => 'deep-research-pro-preview-12-2025',
                'label' => 'Gemini Deep Research Pro Preview',
                'credits_per_1k_input' => 0.2000,
                'credits_per_1k_output' => 1.2000,
                'usd_per_1m_input' => 2.00,
                'usd_per_1m_output' => 12.00,
                'usd_per_1m_reasoning' => 12.00,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => 14.00,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
            [
                'provider' => 'perplexity',
                'model' => 'sonar',
                'label' => 'Perplexity Sonar',
                'credits_per_1k_input' => 0.1000,
                'credits_per_1k_output' => 0.1000,
                'usd_per_1m_input' => 1.00,
                'usd_per_1m_output' => 1.00,
                'usd_per_1m_reasoning' => null,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => 0.005000,
                'is_active' => true,
            ],
            [
                'provider' => 'perplexity',
                'model' => 'sonar-pro',
                'label' => 'Perplexity Sonar Pro',
                'credits_per_1k_input' => 0.3000,
                'credits_per_1k_output' => 1.5000,
                'usd_per_1m_input' => 3.00,
                'usd_per_1m_output' => 15.00,
                'usd_per_1m_reasoning' => null,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => 0.006000,
                'is_active' => true,
            ],
            [
                'provider' => 'perplexity',
                'model' => 'sonar-reasoning-pro',
                'label' => 'Perplexity Sonar Reasoning Pro',
                'credits_per_1k_input' => 0.2000,
                'credits_per_1k_output' => 0.8000,
                'usd_per_1m_input' => 2.00,
                'usd_per_1m_output' => 8.00,
                'usd_per_1m_reasoning' => null,
                'usd_per_1m_citation' => null,
                'usd_per_1k_search_queries' => null,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => 0.006000,
                'is_active' => true,
            ],
            [
                'provider' => 'perplexity',
                'model' => 'sonar-deep-research',
                'label' => 'Perplexity Sonar Deep Research',
                'credits_per_1k_input' => 0.2000,
                'credits_per_1k_output' => 0.8000,
                'usd_per_1m_input' => 2.00,
                'usd_per_1m_output' => 8.00,
                'usd_per_1m_reasoning' => 3.00,
                'usd_per_1m_citation' => 2.00,
                'usd_per_1k_search_queries' => 5.00,
                'min_credits_per_call' => 0,
                'min_usd_per_call' => null,
                'is_active' => true,
            ],
        ];

        foreach ($rows as $row) {
            DB::table('ai_model_pricing')->updateOrInsert(
                [
                    'provider' => $row['provider'],
                    'model' => $row['model'],
                ],
                [
                    'label' => $row['label'],
                    'credits_per_1k_input' => $row['credits_per_1k_input'],
                    'credits_per_1k_output' => $row['credits_per_1k_output'],
                    'usd_per_1m_input' => $row['usd_per_1m_input'],
                    'usd_per_1m_output' => $row['usd_per_1m_output'],
                    'usd_per_1m_reasoning' => $row['usd_per_1m_reasoning'],
                    'usd_per_1m_citation' => $row['usd_per_1m_citation'],
                    'usd_per_1k_search_queries' => $row['usd_per_1k_search_queries'],
                    'min_credits_per_call' => $row['min_credits_per_call'],
                    'min_usd_per_call' => $row['min_usd_per_call'],
                    'is_active' => $row['is_active'],
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
            );
        }
    }

    public function down(): void
    {
        // Keep the refreshed pricing rows in place; do not attempt to restore stale prices.
    }
};
